import { useState, useEffect } from 'react';

const translations = {
  English: {
    home: "Home",
    history: "History",
    analysis: "Analysis",
    bill: "Bill",
    profile: "Profile",
    wattwatcher: "WattWatcher",
    units: "Units",
    kwh: "kWh",
    dailyAvg: "Daily Avg",
    monthlyLimit: "Monthly Limit",
    todaysUsage: "Today's Usage",
    estBill: "Est. Bill",
    carbon: "Carbon",
    billEstimation: "Bill Estimation",
    currentConsumption: "Current Consumption",
    billingPeriod: "Billing Period: Jul 1 - Jul 31, 2026",
    rateBreakdown: "Rate Breakdown",
    unitRate: "Unit Rate",
    unitsConsumed: "Units Consumed",
    fixedCharges: "Fixed Charges",
    estimatedTotal: "Estimated Total",
    estimatedBill: "Estimated Bill",
    lessThanLastMonth: "less than last month",
    payNow: "Pay Now",
    totalConsumption: "Total Consumption",
    actual: "Actual",
    predicted: "Predicted",
    limit: "Limit",
    remaining: "Remaining",
    used: "used",
    aiRecommendations: "AI Recommendations",
    switchLedTitle: "Switch to LED Bulbs",
    switchLedDesc: "Replace incandescent bulbs with LEDs to save up to 75% energy on lighting.",
    optimizeAcTitle: "Optimize AC Temperature",
    optimizeAcDesc: "Set your AC to 24°C instead of 20°C. Each degree saves ~6% energy.",
    offPeakTitle: "Use Off-Peak Hours",
    offPeakDesc: "Run heavy appliances during off-peak hours (10PM-6AM) for lower rates.",
    savePrefix: "Save",
    personalInfo: "Personal Information",
    limitSettings: "Monthly Limit",
    notifications: "Notifications",
    darkMode: "Dark Mode",
    preferences: "Preferences",
    appSettings: "App settings",
    signOut: "Sign Out",
    saveChanges: "Save Changes",
    setMonthlyLimit: "Set Monthly Limit",
    adjustLimitDesc: "Adjust your monthly electricity usage cap",
    saveLimit: "Save Limit",
    language: "Language",
    energyUnit: "Energy Unit",
    savePreferences: "Save Preferences",
    memberSince: "Member Since",
    plan: "Plan",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    welcomeBack: "Welcome Back 👋",
    signInToTrack: "Sign in to track your energy",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    signIn: "Sign In",
    orContinueWith: "Or continue with",
    google: "Google",
    apple: "Apple",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    letsGetStarted: "Let's get started 🚀",
    everyWattCounts: "Every Watt Counts.",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    fieldRequired: "This field is required",
    passwordMismatch: "Passwords do not match",
    payBill: "Pay Bill",
    totalAmountDue: "Total Amount Due",
    payUsing: "Pay using",
    tapAppToPay: "Tap an app to pay instantly",
    open: "Open →",
    securedBy: "Secured by 256-bit encryption",
    processingPayment: "Processing payment...",
    dontClosePage: "Please do not close this page",
    paymentSuccessful: "Payment Successful ✅",
    transactionId: "Transaction ID",
    date: "Date",
    status: "Status",
    completed: "Completed",
    backToBill: "Back to Bill",
    paymentFailed: "Payment Failed ❌",
    txTimedOut: "Transaction timed out. Please try again.",
    tryAgain: "Try Again",
    dailyRecords: "Daily Records",
    lower: "Lower",
    higher: "Higher"
  },
  Tamil: {
    home: "முகப்பு",
    history: "வரலாறு",
    analysis: "பகுப்பாய்வு",
    bill: "கட்டணம்",
    profile: "சுயவிவரம்",
    wattwatcher: "வாட்வாட்சர்",
    units: "அலகுகள்",
    kwh: "கி.வா.ம (kWh)",
    dailyAvg: "தினசரி சராசரி",
    monthlyLimit: "மாதாந்திர வரம்பு",
    todaysUsage: "இன்றைய பயன்பாடு",
    estBill: "மதிப்பீட்டு கட்டணம்",
    carbon: "கார்பன்",
    billEstimation: "கட்டண மதிப்பீடு",
    currentConsumption: "தற்போதைய நுகர்வு",
    billingPeriod: "கட்டண காலம்: ஜூலை 1 - ஜூலை 31, 2026",
    rateBreakdown: "விகித விவரம்",
    unitRate: "அலகு வீதம்",
    unitsConsumed: "நுகரப்பட்ட அலகுகள்",
    fixedCharges: "நிலையான கட்டணங்கள்",
    estimatedTotal: "மதிப்பிடப்பட்ட மொத்தம்",
    estimatedBill: "மதிப்பிடப்பட்ட கட்டணம்",
    lessThanLastMonth: "கடந்த மாதத்தை விட குறைவு",
    payNow: "இப்போது செலுத்துக",
    totalConsumption: "மொத்த நுகர்வு",
    actual: "உண்மையானது",
    predicted: "கணிக்கப்பட்டது",
    limit: "வரம்பு",
    remaining: "மீதமுள்ளது",
    used: "பயன்படுத்தப்பட்டது",
    aiRecommendations: "AI பரிந்துரைகள்",
    switchLedTitle: "LED விளக்குகளுக்கு மாறவும்",
    switchLedDesc: "மின்விளக்குகளை LED விளக்குகளாக மாற்றி 75% வரை மின்சாரத்தை சேமிக்கவும்.",
    optimizeAcTitle: "ஏசி வெப்பநிலையை சீரமைக்கவும்",
    optimizeAcDesc: "ஏசியை 20°Cக்கு பதிலாக 24°Cக்கு வைக்கவும். ஒவ்வொரு டிகிரியும் ~6% மின்சாரத்தை சேமிக்கும்.",
    offPeakTitle: "குறைந்த பயன்பாட்டு நேரத்தை பயன்படுத்தவும்",
    offPeakDesc: "மின்சாரம் குறைவாக செலவாகும் நேரங்களில் (இரவு 10 - காலை 6) கனரக சாதனங்களை இயக்கவும்.",
    savePrefix: "சேமிப்பு",
    personalInfo: "தனிப்பட்ட தகவல்",
    limitSettings: "மாதாந்திர வரம்பு",
    notifications: "அறிவிப்புகள்",
    darkMode: "இருண்ட பயன்முறை",
    preferences: "விருப்பங்கள்",
    appSettings: "பயன்பாட்டு அமைப்புகள்",
    signOut: "வெளியேறு",
    saveChanges: "மாற்றங்களைச் சேமி",
    setMonthlyLimit: "மாதாந்திர வரம்பை அமை",
    adjustLimitDesc: "உங்கள் மாதாந்திர மின்சார பயன்பாட்டு வரம்பை மாற்றியமைக்கவும்",
    saveLimit: "வரம்பைச் சேமி",
    language: "மொழி",
    energyUnit: "ஆற்றல் அலகு",
    savePreferences: "விருப்பங்களைச் சேமி",
    memberSince: "உறுப்பினர் காலம்",
    plan: "திட்டம்",
    fullName: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    phone: "தொலைபேசி",
    address: "முகவரி",
    welcomeBack: "மீண்டும் வருக 👋",
    signInToTrack: "உங்கள் ஆற்றலைக் கண்காணிக்க உள்நுழையவும்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்ததா?",
    signIn: "உள்நுழைக",
    orContinueWith: "அல்லது இதனுடன் தொடரவும்",
    google: "கூகிள்",
    apple: "ஆப்பிள்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    signUp: "பதிவு செய்க",
    letsGetStarted: "தொடங்குவோம் 🚀",
    everyWattCounts: "ஒவ்வொரு வாட்டும் முக்கியம்.",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    createAccount: "கணக்கை உருவாக்கு",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    fieldRequired: "இந்த புலம் தேவைப்படுகிறது",
    passwordMismatch: "கடவுச்சொற்கள் பொருந்தவில்லை",
    payBill: "கட்டணம் செலுத்துக",
    totalAmountDue: "செலுத்த வேண்டிய மொத்த தொகை",
    payUsing: "இதன் மூலம் செலுத்தவும்",
    tapAppToPay: "உடனடியாக செலுத்த ஒரு செயலியைத் தட்டவும்",
    open: "திறக்கவும் →",
    securedBy: "256-பிட் குறியாக்கத்தின் மூலம் பாதுகாக்கப்பட்டது",
    processingPayment: "பரிவர்த்தனை செயலில் உள்ளது...",
    dontClosePage: "தயவுசெய்து இந்தப் பக்கத்தை மூட வேண்டாம்",
    paymentSuccessful: "பரிவர்த்தனை வெற்றி ✅",
    transactionId: "பரிவர்த்தனை எண்",
    date: "தேதி",
    status: "நிலை",
    completed: "முடிந்தது",
    backToBill: "மீண்டும் கட்டணத்திற்கு",
    paymentFailed: "பரிவர்த்தனை தோல்வி ❌",
    txTimedOut: "பரிவர்த்தனை நேரம் முடிந்தது. மீண்டும் முயற்சிக்கவும்.",
    tryAgain: "மீண்டும் முயற்சிக்குக",
    dailyRecords: "தினசரி பதிவுகள்",
    lower: "குறைவு",
    higher: "அதிகம்"
  },
  Hindi: {
    home: "मुख्य पृष्ठ",
    history: "इतिहास",
    analysis: "विश्लेषण",
    bill: "बिल",
    profile: "प्रोफ़ाइल",
    wattwatcher: "वाॅटवाॅचर",
    units: "यूनिट",
    kwh: "kWh",
    dailyAvg: "दैनिक औसत",
    monthlyLimit: "मासिक सीमा",
    todaysUsage: "आज का उपयोग",
    estBill: "अनुमानित बिल",
    carbon: "कार्बन",
    billEstimation: "बिल का अनुमान",
    currentConsumption: "वर्तमान खपत",
    billingPeriod: "बिलिंग अवधि: 1 जुलाई - 31 जुलाई, 2026",
    rateBreakdown: "दर विवरण",
    unitRate: "यूनिट दर",
    unitsConsumed: "खपत की गई यूनिट",
    fixedCharges: "निश्चित शुल्क",
    estimatedTotal: "अनुमानित कुल",
    estimatedBill: "अनुमानित बिल",
    lessThanLastMonth: "पिछले महीने से कम",
    payNow: "अभी भुगतान करें",
    totalConsumption: "कुल खपत",
    actual: "वास्तविक",
    predicted: "पूर्वानुमानित",
    limit: "सीमा",
    remaining: "शेष",
    used: "उपयोग किया गया",
    aiRecommendations: "AI सिफारिशें",
    switchLedTitle: "LED बल्बों का उपयोग करें",
    switchLedDesc: "रोशनी पर 75% तक ऊर्जा बचाने के लिए तापदीप्त बल्बों को LED से बदलें।",
    optimizeAcTitle: "AC तापमान अनुकूलित करें",
    optimizeAcDesc: "अपने AC को 20°C के बजाय 24°C पर सेट करें। प्रत्येक डिग्री लगभग 6% ऊर्जा बचाती है।",
    offPeakTitle: "ऑफ-पीक घंटों का उपयोग करें",
    offPeakDesc: "कम दरों के लिए ऑफ-पीक घंटों (रात 10 बजे से सुबह 6 बजे) के दौरान भारी उपकरणों को चलाएं।",
    savePrefix: "बचत",
    personalInfo: "व्यक्तिगत जानकारी",
    limitSettings: "मासिक सीमा",
    notifications: "अधिसूचनाएं",
    darkMode: "डार्क मोड",
    preferences: "प्राथमिकताएं",
    appSettings: "ऐप सेटिंग्स",
    signOut: "साइन आउट",
    saveChanges: "परिवर्तन सहेजें",
    setMonthlyLimit: "मासिक सीमा निर्धारित करें",
    adjustLimitDesc: "अपनी मासिक बिजली उपयोग सीमा को समायोजित करें",
    saveLimit: "सीमा सहेजें",
    language: "भाषा",
    energyUnit: "ऊर्जा इकाई",
    savePreferences: "प्राथमिकताएं सहेजें",
    memberSince: "सदस्यता काल",
    plan: "योजना",
    fullName: "पूरा नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    address: "पता",
    welcomeBack: "स्वागत है 👋",
    signInToTrack: "अपनी ऊर्जा को ट्रैक करने के लिए साइन इन करें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    signIn: "साइन इन करें",
    orContinueWith: "या इसके साथ जारी रखें",
    google: "गूगल",
    apple: "एप्पल",
    dontHaveAccount: "खाता नहीं है?",
    signUp: "साइन अप करें",
    letsGetStarted: "शुरू करते हैं 🚀",
    everyWattCounts: "हर वाट मायने रखता है।",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    fieldRequired: "यह फ़ील्ड आवश्यक है",
    passwordMismatch: "पासवर्ड मेल नहीं खाते",
    payBill: "बिल भुगतान",
    totalAmountDue: "कुल देय राशि",
    payUsing: "भुगतान का माध्यम",
    tapAppToPay: "तुरंत भुगतान करने के लिए किसी ऐप पर टैप करें",
    open: "खोलें →",
    securedBy: "256-बिट एन्क्रिप्शन द्वारा सुरक्षित",
    processingPayment: "भुगतान संसाधित हो रहा है...",
    dontClosePage: "कृपया इस पृष्ठ को बंद न करें",
    paymentSuccessful: "भुगतान सफल ✅",
    transactionId: "लेनदेन आईडी",
    date: "दिनांक",
    status: "स्थिति",
    completed: "पूर्ण",
    backToBill: "बिल पर वापस जाएं",
    paymentFailed: "भुगतान विफल ❌",
    txTimedOut: "लेनदेन का समय समाप्त हो गया। कृपया पुन: प्रयास करें।",
    tryAgain: "पुनः प्रयास करें",
    dailyRecords: "दैनिक रिकॉर्ड",
    lower: "कम",
    higher: "अधिक"
  },
  Telugu: {
    home: "హోమ్",
    history: "చరిత్ర",
    analysis: "విశ్లేషణ",
    bill: "బిల్లు",
    profile: "ప్రొఫైల్",
    wattwatcher: "వాట్‌వాచర్",
    units: "యూనిట్లు",
    kwh: "kWh",
    dailyAvg: "రోజువారీ సగటు",
    monthlyLimit: "నెలవారీ పరిమితి",
    todaysUsage: "ఈరోజు వాడకం",
    estBill: "అంచనా బిల్లు",
    carbon: "కార్బన్",
    billEstimation: "బిల్లు అంచనా",
    currentConsumption: "ప్రస్తుత వినియోగం",
    billingPeriod: "బిల్లింగ్ కాలం: జూలై 1 - జూలై 31, 2026",
    rateBreakdown: "ధరల వివరాలు",
    unitRate: "యూనిట్ ధర",
    unitsConsumed: "వినియోగించిన యూనిట్లు",
    fixedCharges: "స్థిర ఛార్జీలు",
    estimatedTotal: "అంచనా మొత్తం",
    estimatedBill: "అంచనా బిల్లు",
    lessThanLastMonth: "గత నెల కంటే తక్కువ",
    payNow: "ఇప్పుడే చెల్లించండి",
    totalConsumption: "మొత్తం వినియోగం",
    actual: "వాస్తవ వినియోగం",
    predicted: "అంచనా వినియోగం",
    limit: "పరిమితి",
    remaining: "మిగిలి ఉన్నది",
    used: "వాడినది",
    aiRecommendations: "AI సిఫార్సులు",
    switchLedTitle: "LED బల్బులను వాడండి",
    switchLedDesc: "వెలుతురు కోసం వాడే బల్బులను LED బల్బులతో మార్చడం ద్వారా 75% వరకు విద్యుత్‌ను ఆదా చేయవచ్చు.",
    optimizeAcTitle: "AC ఉష్ణోగ్రతను సరిచేయండి",
    optimizeAcDesc: "మీ AC ని 20°C కు బదులుగా 24°C లో ఉంచండి. ప్రతి డిగ్రీకి దాదాపు 6% విద్యుత్ ఆదా అవుతుంది.",
    offPeakTitle: "తక్కువ వాడకం ఉన్న సమయాలను వాడండి",
    offPeakDesc: "తక్కువ ఛార్జీలు ఉండే సమయాల్లో (రాత్రి 10 నుండి ఉదయం 6 వరకు) ఎక్కువ విద్యుత్ వాడే పరికరాలను నడపండి.",
    savePrefix: "ఆదా",
    personalInfo: "వ్యక్తిగత సమాచారం",
    limitSettings: "నెలవారీ పరిమితి",
    notifications: "నోటిఫికేషన్లు",
    darkMode: "డార్క్ మోడ్",
    preferences: "ప్రాధాన్యతలు",
    appSettings: "యాప్ సెట్టింగ్స్",
    signOut: "సైన్ అవుట్",
    saveChanges: "మార్పులను సేవ్ చేయి",
    setMonthlyLimit: "నెలవారీ పరిమితిని సెట్ చేయి",
    adjustLimitDesc: "మీ నెలవారీ విద్యుత్ వాడకం పరిమితిని సర్దుబాటు చేయండి",
    saveLimit: "పరిమితిని సేవ్ చేయి",
    language: "భాషా",
    energyUnit: "శక్తి ప్రమాణం",
    savePreferences: "ప్రాధాన్యతలను సేవ్ చేయి",
    memberSince: "సభ్యత్వ కాలం",
    plan: "ప్లాన్",
    fullName: "పూర్తి పేరు",
    email: "ఈమెయిల్",
    phone: "ఫోన్",
    address: "చిరునామా",
    welcomeBack: "స్వాగతం 👋",
    signInToTrack: "మీ విద్యుత్ వినియోగాన్ని ట్రాక్ చేయడానికి సైన్ ఇన్ చేయండి",
    emailAddress: "ఈమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    signIn: "సైన్ ఇన్",
    orContinueWith: "లేదా దీనితో కొనసాగించండి",
    google: "గూగుల్",
    apple: "యాపిల్",
    dontHaveAccount: "ఖాతా లేదా?",
    signUp: "సైన్ అప్",
    letsGetStarted: "ప్రారంభిద్దాం 🚀",
    everyWattCounts: "ప్రతి వాట్ ముఖ్యమైనదే.",
    confirmPassword: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    createAccount: "ఖాతాను సృష్టించు",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    fieldRequired: "ఈ ఫీల్డ్ తప్పనిసరి",
    passwordMismatch: "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
    payBill: "బిల్లు చెల్లింపు",
    totalAmountDue: "చెల్లించవలసిన మొత్తం",
    payUsing: "దీని ద్వారా చెల్లించండి",
    tapAppToPay: "వెంటనే చెల్లించడానికి ఏదైనా యాప్‌ను నొక్కండి",
    open: "ఓపెన్ చేయి →",
    securedBy: "256-బిట్ ఎన్‌క్రిప్షన్ ద్వారా సురక్షితం",
    processingPayment: "చెలింపు ప్రక్రియ జరుగుతోంది...",
    dontClosePage: "దయచేసి ఈ పేజీని మూసివేయవద్దు",
    paymentSuccessful: "చెల్లింపు విజయవంతమైంది ✅",
    transactionId: "లావాదేవీ ఐడి",
    date: "తేదీ",
    status: "స్థితి",
    completed: "పూర్తయింది",
    backToBill: "మళ్లీ బిల్లుకు",
    paymentFailed: "చెల్లింపు విఫలమైంది ❌",
    txTimedOut: "లావాదేవీ సమయం ముగిసింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    tryAgain: "మళ్లీ ప్రయత్నించు",
    dailyRecords: "రోజువారీ రికార్డులు",
    lower: "తక్కువ",
    higher: "ఎక్కువ"
  }
};

export const getLanguage = () => {
  return localStorage.getItem('wattwatcher_lang') || 'English';
};

export const setLanguage = (lang) => {
  localStorage.setItem('wattwatcher_lang', lang);
  window.dispatchEvent(new Event('languageChange'));
};

export const useTranslation = () => {
  const [lang, setLang] = useState(getLanguage());

  useEffect(() => {
    const handleLangChange = () => {
      setLang(getLanguage());
    };
    window.addEventListener('languageChange', handleLangChange);
    return () => {
      window.removeEventListener('languageChange', handleLangChange);
    };
  }, []);

  return {
    t: (key) => translations[lang]?.[key] || translations['English']?.[key] || key,
    currentLanguage: lang,
    setLanguage
  };
};

export const getEnergyUnit = () => {
  return localStorage.getItem('wattwatcher_unit') || 'kWh';
};

export const setEnergyUnit = (unit) => {
  localStorage.setItem('wattwatcher_unit', unit);
  window.dispatchEvent(new Event('unitChange'));
};

export const useUnit = () => {
  const [unit, setUnit] = useState(getEnergyUnit());

  useEffect(() => {
    const handleUnitChange = () => {
      setUnit(getEnergyUnit());
    };
    window.addEventListener('unitChange', handleUnitChange);
    return () => {
      window.removeEventListener('unitChange', handleUnitChange);
    };
  }, []);

  const format = (value, rawUnitOnly = false) => {
    if (rawUnitOnly) return unit;
    if (unit === 'MWh') {
      return `${(value / 1000).toFixed(3)} MWh`;
    }
    return `${value} ${unit}`;
  };

  return {
    unit,
    setEnergyUnit,
    format
  };
};
